name: Deploy to staging

on:
  push:

    branches:
      - "main"


jobs:
  redeploy_frontend:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:

       - run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
          echo "${{secrets.KNOWN_HOSTS}}" &> ~/.ssh/Known_hosts
          ssh -i ~/.ssh/id_rsa ubuntu@34.194.131.148
          cd ci-test-deploy/ && git pull
          pnpm install
          pnpm run build
          pm2 restart fe-server
          pm2 restart http-server
          pm2 restart ws-serve

